[package]
name = "hol_screens"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdev = {version = "0.5.3", features= ["unstable_grab"]}
screenshots = "0.8.10"
chrono="0.4.31"